In [1]:
import numpy as np

In [2]:
marks = [
    [98, 99, 100],
    [93, 89, 87],
    [99, 100, 67]
]

In [6]:
n1 = np.array(marks)
print(n1)
print(type(n1))
print(n1.ndim)
print(n1.shape)

[[ 98  99 100]
 [ 93  89  87]
 [ 99 100  67]]
<class 'numpy.ndarray'>
2
(3, 3)


In [11]:
# indexing
print(n1[0])
print(n1[[0, -1]])

# row + column indexing
print(n1[-1][1]) # python way. Not optimal
print(n1[-1, 1]) # numpy way and optimal

[ 98  99 100]
[[ 98  99 100]
 [ 99 100  67]]
100
100


In [17]:
# slicing
print(n1[:2])
print(n1[:2, 1:]) # row + column level slicing too

# slicing + indexing
print(n1[-2:, [0, -1]]) # row slicing + column multi indexing

# indexing + slicing
print(n1[[0, -1], :2]) # row multi indexing + column slicing

[[ 98  99 100]
 [ 93  89  87]]
[[ 99 100]
 [ 89  87]]
[[93 87]
 [99 67]]
[[ 98  99]
 [ 99 100]]


In [26]:
print(n1)
n2 = n1[[0, -1]]
print(n2[:, [0, -1]])

[[ 98  99 100]
 [ 93  89  87]
 [ 99 100  67]]
[[ 98 100]
 [ 99  67]]


In [21]:
print(n1)
print(n1.mean(axis=0))
print(n1.sum(axis=1))

[[ 98  99 100]
 [ 93  89  87]
 [ 99 100  67]]
[96.66666667 96.         84.66666667]
[297 269 266]


In [28]:
print(n1)
n3 = n1 - 1
print(n3)

[[ 98  99 100]
 [ 93  89  87]
 [ 99 100  67]]
[[97 98 99]
 [92 88 86]
 [98 99 66]]


In [30]:
print(n1)
n4 = n1 - [1, 0, 1]
print(n4)

[[ 98  99 100]
 [ 93  89  87]
 [ 99 100  67]]
[[ 97  99  99]
 [ 92  89  86]
 [ 98 100  66]]


In [32]:
print(n1)
n5 = n1 - [[1],
          [0],
          [1]]
print(n5)

[[ 98  99 100]
 [ 93  89  87]
 [ 99 100  67]]
[[97 98 99]
 [93 89 87]
 [98 99 66]]


In [33]:
n6 = np.array([
    [4, 3],
    [2, 1]
])
n7 = np.array([
    [2, 6],
    [9, 4]
])

In [34]:
print(n6)
print(n7)

[[4 3]
 [2 1]]
[[2 6]
 [9 4]]


In [39]:
print(n6 + n7)
print(n6 - n7)
print(n6 * n7) # this is not matrix multiplication
print(np.dot(n6, n7)) # matrix multiplication

[[ 6  9]
 [11  5]]
[[ 2 -3]
 [-7 -3]]
[[ 8 18]
 [18  4]]
[[35 36]
 [13 16]]
