In [5]:
import numpy as np
import numpy.random as rd

In [4]:
print(np.zeros(10))
print(np.ones(21))
print(np.arange(3, 27))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]


In [21]:
print(rd.rand(10))
print(rd.randn(10))
print(rd.randn(3,3))

[0.4315024  0.51906653 0.83471855 0.10775014 0.24545523 0.08454828
 0.96417967 0.70661218 0.87300033 0.64073112]
[ 0.5015568  -0.02078064 -0.49351379  0.35397915  0.78536768 -0.38531517
 -0.8821678   1.37092019 -0.67192409  1.08196611]
[[ 0.91459235  1.44936956  0.68773054]
 [-1.5458144   0.23806155  1.03466642]
 [ 0.19576685 -0.50529277  0.41268411]]


In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
n1 = np.arange(1, 10)
print(n1)
n2 = n1.reshape(3, 3)
print(n2)
n3 = n2.ravel()
print(n3)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
