In [43]:
import numpy as np

In [44]:
marks = [4, 5, 4, 10, 7, 8, 10, 1, 2, 4, 6]

In [45]:
# ndarray
n1 = np.array(marks, dtype=np.int8)
print(type(n1))
print(n1)
print(marks)
print(n1.ndim)
print(n1.shape)
print(n1.dtype)

<class 'numpy.ndarray'>
[ 4  5  4 10  7  8 10  1  2  4  6]
[4, 5, 4, 10, 7, 8, 10, 1, 2, 4, 6]
1
(11,)
int8


In [46]:
# indexing
print(n1[0])
print(n1[1])
print(n1[-1])
print(n1[-3])

# multiindexing
print(n1[[0, -1]])

4
5
6
2
[4 6]


In [47]:
# indexing + modification
n1[2] = 6
print(n1)

# multiindexing + modification
n1[[0, -1]] = [n1[-1], n1[0]]
print(n1)

[ 4  5  6 10  7  8 10  1  2  4  6]
[ 6  5  6 10  7  8 10  1  2  4  4]


In [48]:
n1[[-2, -3]] = 0
print(n1)

[ 6  5  6 10  7  8 10  1  0  0  4]


In [49]:
# slicing
print(n1)
print(n1[0:3])
print(n1[:3])
print(n1[3:])

# negative slicing
print(n1[-4:])
print(n1[-4:-1])

[ 6  5  6 10  7  8 10  1  0  0  4]
[6 5 6]
[6 5 6]
[10  7  8 10  1  0  0  4]
[1 0 0 4]
[1 0 0]


In [50]:
# slicing + modification
print(n1)
n1[:2] = 0
print(n1)

[ 6  5  6 10  7  8 10  1  0  0  4]
[ 0  0  6 10  7  8 10  1  0  0  4]


In [51]:
print(n1)
print(n1[::-1])

[ 0  0  6 10  7  8 10  1  0  0  4]
[ 4  0  0  1 10  8  7 10  6  0  0]


In [52]:
# arithmetic operations
print(n1)
n2 = n1 - 1
print(n2)
n3 = n1 ** 2
print(n3)

[ 0  0  6 10  7  8 10  1  0  0  4]
[-1 -1  5  9  6  7  9  0 -1 -1  3]
[  0   0  36 100  49  64 100   1   0   0  16]


In [53]:
# relational operations
print(n1)
n4 = n1 == 10
print(n4)
n5 = (n1 == 10) | (n1 < 5)
print(n5)

[ 0  0  6 10  7  8 10  1  0  0  4]
[False False False  True False False  True False False False False]
[ True  True False  True False False  True  True  True  True  True]


In [57]:
# filtering
print(n1)
n6 = n1[n1 > 5]
print(n6)

n7 = n1[(n1 == 10) | (n1 < 5)]
print(n7)

[ 0  0  6 10  7  8 10  1  0  0  4]
[ 6 10  7  8 10]
[ 0  0 10 10  1  0  0  4]


In [64]:
# descriptive statistics
print(n1)
print(n1.min())
print(n1.max())
print(n1.mean())
print(np.median(n1))
print(n1.std())
print(n1.var())

[ 0  0  6 10  7  8 10  1  0  0  4]
0
10
4.181818181818182
4.0
3.9730497060749377
15.785123966942148


In [68]:
print(n1)
print(np.unique(n1))
print(np.unique(n1, return_counts=True))

[ 0  0  6 10  7  8 10  1  0  0  4]
[ 0  1  4  6  7  8 10]
(array([ 0,  1,  4,  6,  7,  8, 10], dtype=int8), array([4, 1, 1, 1, 1, 1, 2]))


In [71]:
print(n1)
n8 = np.sort(n1)[::-1]
print(n8)

[ 0  0  6 10  7  8 10  1  0  0  4]
[10 10  8  7  6  4  1  0  0  0  0]


In [73]:
print(n1)
# categorize
n9 = np.where(n1 > 6, 1, 0)
print(n9)

[ 0  0  6 10  7  8 10  1  0  0  4]
[0 0 0 1 1 1 1 0 0 0 0]
